modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/terrarium-earth/prometheus/issues"

[[mods]]
modId = "prometheus"
version = "${version}"
displayName = "Prometheus"
updateJSONURL = "https://api.modrinth.com/updates/iYcNKH7W/forge_updates.json"
displayURL = "https://modrinth.com/mod/prometheus"
logoFile = "prometheus_icon.png"
authors = "ThatGravyBoat"
credits = ""
description = "Modern Ranks/Utilities Mod!"

[[dependencies.prometheus]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.prometheus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.prometheus]]
modId = "resourcefullib"
mandatory = true
versionRange = "[2.1.1,)"
ordering = "NONE"
side = "BOTH"