modLoader = "javafml"
loaderVersion = "[45,)"
license = "MIT"
issueTrackerURL = "https://github.com/terrarium-earth/${github_name}/issues"

[[mods]]
modId = "prometheus"
version = "${version}"
displayName = "Prometheus"
updateJSONURL = "https://api.modrinth.com/updates/${modrinth_id}/forge_updates.json"
displayURL = "https://modrinth.com/mod/prometheus"
logoFile = "icon.png"
authors = "ThatGravyBoat"
credits = ""
description = "Modern Utilities Mod!"

[[dependencies.prometheus]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.prometheus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.prometheus]]
modId = "resourcefullib"
mandatory = true
versionRange = "[${resourcefullib_version},)"
ordering = "NONE"
side = "BOTH"