modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/terrarium-earth/prometheus/issues"

[[mods]]
modId = "prometheus"
version = "${version}"
displayName = "Prometheus"
updateJSONURL = "https://api.modrinth.com/updates/iYcNKH7W/forge_updates.json"
displayURL = "https://modrinth.com/mod/prometheus"
logoFile = "prometheus_icon.png"
authors = "ThatGravyBoat"
credits = ""
description = "A utility mod adding useful commands and player permission handling."

[[mixins]]
config = "prometheus-common.mixins.json"

[[dependencies.prometheus]]
modId = "neoforge"
type="required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.prometheus]]
modId = "minecraft"
type="required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.prometheus]]
modId = "resourcefullib"
type="required"
versionRange = "[2.4.3,)"
ordering = "NONE"
side = "BOTH"